import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  console.log(router.query);
  return (
    <main className='d-flex flex-column min-vh-100'>
      <Head>
        <title>Next.js + Bootstrap ❤️</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <div className='container my-5'>
        <div className='row justify-content-center'>
          <div className='col-12 col-md-4'>
            <h2>SSO Login Demo</h2>
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">Email address</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com" />
            </div>
            <div class="mb-3">
              <label for="exampleFormControlInput1" class="form-label">Password</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="password" />
            </div>

            <button className='btn btn-primary w-100' onClick={() => {
              window.open(router.query.redirect);
            }}>Authenticate</button>

            <div className='text-align-center my-3' style={{ textAlign: "center" }}>
              You will be redirected to {`{${router.query.redirect}}`} after you login;
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </main>
  );
}
